version: '3'

services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel-app
    restart: always
    ports:
      - 8080:9000
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: faturas_db
      DB_USERNAME: root
      DB_PASSWORD:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: faturas_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data: